Viser skjemaet for redigering og en melding når brukeren er UKM Norge
UKMNorge/UKMmonstring pull request #58
Opened 2021-04-19 15:50 UTC by slogan-15

Close #57.

Tid: 1 time og 30 minutter.

2021-04-19 16:00 UTC, jardarn commented
ok by me

2021-04-19 16:04 UTC, jardarn approved these changes

2021-04-20 08:40 UTC, mariusmandal requested changes

2021-04-20 08:40 UTC, mariusmandal commented on controller/monstring.controller.php
> +    if ($arrangement->erFerdig() && wp_get_current_user()->user_login != 'UKM Norge') {
bruk heller `is_super_admin()` her (eller `is_superadmin()`) - da funker det for alle superadmin-brukere

2021-04-20 14:22 UTC, mariusmandal approved these changes

2021-04-20 14:23 UTC, merged